---
# docker run

- hosts: eindopdracht
  user: root
  tasks:
  - name: webtest angular starten
    docker_container:
      name: webtest
      image: nginx
      state: started
      restart: yes
      volumes:
        - /home/acant/webtest:/usr/share/nginx/html
      ports:
        - 8200:80
  - name: copying files to remote host
    copy:
      src: /var/jenkins_home/workspace/Eindopdracht_freestyle/dist
      dest: /home/acant/webtest



